### ISSUE TITLE
saving h5/xml file as tif

### ISSUE THREAD

**Issue by pawlowska** [bigdataviewer/bigdataviewer_fiji#15]
Is it possible to save a h5/xml dataset as .tif?

**Comment by tpietzsch** [comment]
You can install the BigStitcher Fiji plugin (see https://imagej.net/BigStitcher) and then use `Plugins > BigStitcher > Batch Processing > Resave > As TIFF ...`

**Comment by pawlowska** [comment]
@tpietzsch  both resaving and saving of fused image stopped working for me in BigStitcher some time ago and recent updates didn't solve it. I opened an issue about it https://github.com/PreibischLab/BigStitcher/issues/58 but there is no answer, so I was hoping to find a workaround by fusing to h5 first and then saving as tiff.

**Comment by tpietzsch** [comment]
@pawlowska Oh... sorry, no, there is no save-as-tiff functionality in BigDataViewer itself.

Depending on what you want, you can possibly create a macro.
You can open a particular stack from a h5/xml using `File > Import > BigDataViewer...` as a normal ImageJ stack (this is macro-recordable), then save to a TIFF file, etc. Not ideal, but if it's just for one or two datasets, you can probably automate it in this way?

Also, I would recommend asking the question on the forum.image.sc, if you haven't yet. It might get more attention there than a github issue.

**Comment by pawlowska** [comment]
Thanks, this works as a workaround. Since we need to do some other preprocessing on the tif file (such as scaling by a factor that is not power of 2), it's not even that annoying.

I posted on the forum. Turns out there is at least one other person with this problem.

**Comment by saskra** [comment]
> You can install the BigStitcher Fiji plugin (see https://imagej.net/BigStitcher) and then use `Plugins > BigStitcher > Batch Processing > Resave > As TIFF ...`

Unfortunately I only get the single tiles back and not the stitched overall picture.

> I posted on the forum. Turns out there is at least one other person with this problem.

Can you write the link to your post in the forum here?
