### ISSUE TITLE
Manual transformation of group not working in BDV 6.2.0

### ISSUE THREAD

**Issue by zifredder** [bigdataviewer/bigdataviewer_fiji#17]
When in fused group mode, pressing `T` should enable one to manually transform all objects in the current group. Instead, BDV does nothing and this is printed to the console:
```
Exception in thread "AWT-EventQueue-0" java.lang.StackOverflowError
	at bdv.viewer.UnmodifiableViewerState.getSourcesInGroup(UnmodifiableViewerState.java:328)
	at bdv.viewer.UnmodifiableViewerState.getSourcesInGroup(UnmodifiableViewerState.java:328)
	at bdv.viewer.UnmodifiableViewerState.getSourcesInGroup(UnmodifiableViewerState.java:328)
	(...)
```

I use BigStitcher, which uses BDV 6.2.0, where this bug appears. A fresh Fiji installation without BigStitcher comes with BDV 6.0.0, where group transformation works as expected.
I hope this is the right place for this issue; otherwise please let me know, then I will post it to the BigStitcher repo.

Platform info:
Windows 10 Education 1803 64 bit
ImageJ 1.53a
Big_Stitcher-0.5.5
bigdataviewer_fiji-6.2.0

Cheers

**Comment by tpietzsch** [comment]
Thanks! It should be fixed now. Could you check with https://maven.scijava.org/service/local/repositories/snapshots/content/sc/fiji/bigdataviewer-core/9.0.5-SNAPSHOT/bigdataviewer-core-9.0.5-20200508.123904-2.jar
If that fixes it as expected, I will make new release...

**Comment by zifredder** [comment]
Works! Thanks for the quick fix.

**Comment by tpietzsch** [comment]
Ok, I released bigdataviewer-core-9.0.5.
@StephanPreibisch Could you update it on the BigStitcher update site?
https://maven.scijava.org/service/local/repositories/releases/content/sc/fiji/bigdataviewer-core/9.0.5/bigdataviewer-core-9.0.5.jar

**Comment by StephanPreibisch** [comment]
Hi, thanks Tobi, no other dependencies?

**Comment by tpietzsch** [comment]
No just bigdataviewer-core. Thanks!!!

**Comment by StephanPreibisch** [comment]
done, thanks @tpietzsch
