### ISSUE TITLE
"File>Import>BigDataViewer..." with resolution level > 0 gives incorrect scale

### ISSUE THREAD

**Issue by martlj** [bigdataviewer/bigdataviewer_fiji#3]
When importing an image from a BDV file using "File>Import>BigDataViewer...", the pixel size seems to be fixed at full-resolution value regardless of which resolution level is chosen for import, resulting in 2x, 4x, 8x etc. errors in scale in the output images.

Using bigdataviewer_fiji-2.0.0 plugin and ImageJ 1.50e.

**Comment by tpietzsch** [comment]
This should be fixed by f160710de2ab95da23654fd21e0b03e31bd787a6
I'll release a new version soon
